python train.py --train_dir "/mnt/disk1/phucnp/Dataset/df_in_the_wild/image/train" --val_dir "/mnt/disk1/phucnp/Dataset/df_in_the_wild/image/test" --batch_size 64 --lr 3e-4 --n_epochs 25 --image_size 128 --workers 8 --checkpoint "df_in_the_wild_checkpoint/dual_efficient_vit" --resume "" --gpu_id 1 --es_patience 5 --es_metric "val_acc" --loss "wbce" dual_efficient_vit --version "cross_attention-freq-add" --weight 1 --patch_size 1
# python train.py --train_dir "/mnt/disk1/phucnp/Dataset/df_in_the_wild/image/train" --val_dir "/mnt/disk1/phucnp/Dataset/df_in_the_wild/image/test" --batch_size 64 --lr 3e-4 --n_epochs 25 --image_size 128 --workers 8 --checkpoint "df_in_the_wild_checkpoint/dual_efficient_vit" --resume "" --gpu_id 1 --es_patience 5 --es_metric "val_acc" --loss "wbce" dual_efficient_vit --version "cross_attention-freq-add" --weight 1 --patch_size 2
# python train.py --train_dir "/mnt/disk1/phucnp/Dataset/df_in_the_wild/image/train" --val_dir "/mnt/disk1/phucnp/Dataset/df_in_the_wild/image/test" --batch_size 64 --lr 3e-4 --n_epochs 25 --image_size 128 --workers 8 --checkpoint "df_in_the_wild_checkpoint/dual_efficient_vit" --resume "" --gpu_id 1 --es_patience 5 --es_metric "val_acc" --loss "wbce" dual_efficient_vit --version "cross_attention-freq-add" --weight 1 --patch_size 2
# #
# python train.py --train_dir "/mnt/disk1/phucnp/Dataset/df_in_the_wild/image/train" --val_dir "/mnt/disk1/phucnp/Dataset/df_in_the_wild/image/test" --batch_size 64 --lr 3e-4 --n_epochs 25 --image_size 128 --workers 8 --checkpoint "df_in_the_wild_checkpoint/dual_efficient_vit" --resume "" --gpu_id 1 --es_patience 5 --es_metric "val_acc" --loss "wbce" dual_efficient_vit --version "cross_attention-freq-add" --weight 1 --patch_size 1
# #
# python train.py --train_dir "/mnt/disk1/phucnp/Dataset/df_in_the_wild/image/train" --val_dir "/mnt/disk1/phucnp/Dataset/df_in_the_wild/image/test" --batch_size 64 --lr 3e-4 --n_epochs 25 --image_size 128 --workers 8 --checkpoint "df_in_the_wild_checkpoint/dual_efficient_vit" --resume "" --gpu_id 1 --es_patience 5 --es_metric "val_acc" --loss "wbce" dual_efficient_vit --version "cross_attention-freq-cat" --weight 1 --patch_size 2
# python train.py --train_dir "/mnt/disk1/phucnp/Dataset/df_in_the_wild/image/train" --val_dir "/mnt/disk1/phucnp/Dataset/df_in_the_wild/image/test" --batch_size 64 --lr 3e-4 --n_epochs 25 --image_size 128 --workers 8 --checkpoint "df_in_the_wild_checkpoint/dual_efficient_vit" --resume "" --gpu_id 1 --es_patience 5 --es_metric "val_acc" --loss "wbce" dual_efficient_vit --version "cross_attention-freq-cat" --weight 1 --patch_size 1
# # 
# python train.py --train_dir "/mnt/disk1/phucnp/Dataset/df_in_the_wild/image/train" --val_dir "/mnt/disk1/phucnp/Dataset/df_in_the_wild/image/test" --batch_size 64 --lr 3e-4 --n_epochs 25 --image_size 128 --workers 8 --checkpoint "df_in_the_wild_checkpoint/dual_efficient_vit" --resume "" --gpu_id 1 --es_patience 5 --es_metric "val_acc" --loss "wbce" dual_efficient_vit --version "cross_attention-freq-add" --weight 0.6 --patch_size 2
# python train.py --train_dir "/mnt/disk1/phucnp/Dataset/df_in_the_wild/image/train" --val_dir "/mnt/disk1/phucnp/Dataset/df_in_the_wild/image/test" --batch_size 64 --lr 3e-4 --n_epochs 25 --image_size 128 --workers 8 --checkpoint "df_in_the_wild_checkpoint/dual_efficient_vit" --resume "" --gpu_id 1 --es_patience 5 --es_metric "val_acc" --loss "wbce" dual_efficient_vit --version "cross_attention-freq-add" --weight 0.6 --patch_size 1
# python train.py --train_dir "/mnt/disk1/phucnp/Dataset/df_in_the_wild/image/train" --val_dir "/mnt/disk1/phucnp/Dataset/df_in_the_wild/image/test" --batch_size 64 --lr 3e-4 --n_epochs 25 --image_size 128 --workers 8 --checkpoint "df_in_the_wild_checkpoint/dual_efficient_vit" --resume "" --gpu_id 1 --es_patience 5 --es_metric "val_acc" --loss "wbce" dual_efficient_vit --version "cross_attention-freq-cat" --weight 0.6 --patch_size 2
# python train.py --train_dir "/mnt/disk1/phucnp/Dataset/df_in_the_wild/image/train" --val_dir "/mnt/disk1/phucnp/Dataset/df_in_the_wild/image/test" --batch_size 64 --lr 3e-4 --n_epochs 25 --image_size 128 --workers 8 --checkpoint "df_in_the_wild_checkpoint/dual_efficient_vit" --resume "" --gpu_id 1 --es_patience 5 --es_metric "val_acc" --loss "wbce" dual_efficient_vit --version "cross_attention-freq-cat" --weight 0.6 --patch_size 1
# # 
# python train.py --train_dir "/mnt/disk1/phucnp/Dataset/df_in_the_wild/image/train" --val_dir "/mnt/disk1/phucnp/Dataset/df_in_the_wild/image/test" --batch_size 32 --lr 3e-4 --n_epochs 25 --image_size 128 --workers 8 --checkpoint "df_in_the_wild_checkpoint/dual_efficient_vit" --resume "" --gpu_id 0 --es_patience 5 --es_metric "val_acc" --loss "wbce" dual_efficient_vit --version "cross_attention-spatial-add" --weight 1 --patch_size 2
# python train.py --train_dir "/mnt/disk1/phucnp/Dataset/df_in_the_wild/image/train" --val_dir "/mnt/disk1/phucnp/Dataset/df_in_the_wild/image/test" --batch_size 32 --lr 3e-4 --n_epochs 25 --image_size 128 --workers 8 --checkpoint "df_in_the_wild_checkpoint/dual_efficient_vit" --resume "" --gpu_id 0 --es_patience 5 --es_metric "val_acc" --loss "wbce" dual_efficient_vit --version "cross_attention-spatial-add" --weight 1 --patch_size 1
# python train.py --train_dir "/mnt/disk1/phucnp/Dataset/df_in_the_wild/image/train" --val_dir "/mnt/disk1/phucnp/Dataset/df_in_the_wild/image/test" --batch_size 32 --lr 3e-4 --n_epochs 25 --image_size 128 --workers 8 --checkpoint "df_in_the_wild_checkpoint/dual_efficient_vit" --resume "" --gpu_id 0 --es_patience 5 --es_metric "val_acc" --loss "wbce" dual_efficient_vit --version "cross_attention-spatial-cat" --weight 1 --patch_size 2
# python train.py --train_dir "/mnt/disk1/phucnp/Dataset/df_in_the_wild/image/train" --val_dir "/mnt/disk1/phucnp/Dataset/df_in_the_wild/image/test" --batch_size 32 --lr 3e-4 --n_epochs 25 --image_size 128 --workers 8 --checkpoint "df_in_the_wild_checkpoint/dual_efficient_vit" --resume "" --gpu_id 0 --es_patience 5 --es_metric "val_acc" --loss "wbce" dual_efficient_vit --version "cross_attention-spatial-cat" --weight 1 --patch_size 1
# # 
# python train.py --train_dir "/mnt/disk1/phucnp/Dataset/df_in_the_wild/image/train" --val_dir "/mnt/disk1/phucnp/Dataset/df_in_the_wild/image/test" --batch_size 32 --lr 3e-4 --n_epochs 25 --image_size 128 --workers 8 --checkpoint "df_in_the_wild_checkpoint/dual_efficient_vit" --resume "" --gpu_id 0 --es_patience 5 --es_metric "val_acc" --loss "wbce" dual_efficient_vit --version "merge-add" --weight 0.8 --patch_size 2
# python train.py --train_dir "/mnt/disk1/phucnp/Dataset/df_in_the_wild/image/train" --val_dir "/mnt/disk1/phucnp/Dataset/df_in_the_wild/image/test" --batch_size 32 --lr 3e-4 --n_epochs 25 --image_size 128 --workers 8 --checkpoint "df_in_the_wild_checkpoint/dual_efficient_vit" --resume "" --gpu_id 0 --es_patience 5 --es_metric "val_acc" --loss "wbce" dual_efficient_vit --version "merge-add" --weight 0.8 --patch_size 1
# python train.py --train_dir "/mnt/disk1/phucnp/Dataset/df_in_the_wild/image/train" --val_dir "/mnt/disk1/phucnp/Dataset/df_in_the_wild/image/test" --batch_size 32 --lr 3e-4 --n_epochs 25 --image_size 128 --workers 8 --checkpoint "df_in_the_wild_checkpoint/dual_efficient_vit" --resume "" --gpu_id 0 --es_patience 5 --es_metric "val_acc" --loss "wbce" dual_efficient_vit --version "merge-cat" --weight 0.8 --patch_size 2
# python train.py --train_dir "/mnt/disk1/phucnp/Dataset/df_in_the_wild/image/train" --val_dir "/mnt/disk1/phucnp/Dataset/df_in_the_wild/image/test" --batch_size 32 --lr 3e-4 --n_epochs 25 --image_size 128 --workers 8 --checkpoint "df_in_the_wild_checkpoint/dual_efficient_vit" --resume "" --gpu_id 0 --es_patience 5 --es_metric "val_acc" --loss "wbce" dual_efficient_vit --version "merge-cat" --weight 0.8 --patch_size 1